# Generated by Django 2.2 on 2020-06-14 22:12

import courses.models.courses
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Title')),
                ('course_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Course details')),
                ('course_image', models.FileField(blank=True, null=True, upload_to=courses.models.courses.upload_image_path, verbose_name='Course cover image')),
                ('course_intro_video', models.URLField(blank=True, default='http://', max_length=500, null=True, verbose_name='Course video url')),
                ('course_complete_duration', models.CharField(max_length=10, verbose_name='Duration')),
                ('course_for', models.CharField(choices=[('beginner', ' BEGINNER'), ('intermediate', 'INTERMEDIATE'), ('advance', 'ADVANCED')], default='Select For', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Featured course')),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title_01', models.CharField(blank=True, max_length=150, null=True)),
                ('video_01', models.URLField(blank=True, max_length=500, null=True)),
                ('video_duration_01', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lession title')),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('lessons_intro_video', models.URLField(max_length=250)),
                ('lessons_duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_locked', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('course_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Section Title: ')),
                ('lessons_intro_video', models.URLField(max_length=250)),
                ('lessons_duration', models.CharField(max_length=10, verbose_name='Duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('lesson_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Topic Title: ')),
                ('lessons_video', models.URLField(max_length=250)),
                ('lessons_duration', models.CharField(blank=True, max_length=3, null=True, verbose_name='Duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('section_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Section')),
            ],
        ),
    ]
