# Generated by Django 2.2 on 2020-06-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='title',
            new_name='section_title',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='topic_title',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='title',
        ),
        migrations.RemoveField(
            model_name='section',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lessons title'),
        ),
    ]
