# Generated by Django 2.2 on 2020-06-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200616_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Course Title'),
        ),
    ]
