# Generated by Django 2.2 on 2020-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200617_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_intro_video',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Course video url'),
        ),
    ]
