# Generated by Django 2.2 on 2020-06-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200617_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='cover_image',
        ),
    ]
