# Generated by Django 2.2 on 2020-06-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQManager',
        ),
    ]
