# Generated by Django 2.2 on 2020-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='package_for',
            field=models.CharField(choices=[('student', ' Student'), ('team', 'Team'), ('enterprise', 'Enterprise')], max_length=20),
        ),
    ]
