# Generated by Django 2.2 on 2020-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20200620_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='package_for',
        ),
        migrations.AlterField(
            model_name='pricing',
            name='package_title',
            field=models.CharField(choices=[('student', ' Student'), ('team', 'Team'), ('enterprise', 'Enterprise')], default=12.12, max_length=20),
            preserve_default=False,
        ),
    ]
