# Generated by Django 2.2 on 2020-06-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20200620_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='bill_cycle',
            field=models.CharField(choices=[('month', ' Month'), ('year', 'Year')], default=12.23, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='package_price',
            field=models.IntegerField(default=12.12),
            preserve_default=False,
        ),
    ]
