# Generated by Django 2.2 on 2020-06-15 20:55

from django.db import migrations, models
import lms.utils_file


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200615_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=lms.utils_file.upload_image_path),
        ),
    ]
